#ifndef __CONST__
#define __CONST__
#define BILLION 1000000000

/** FRAME*/
#define HEIGHT_FRAME 500
#define WIDTH_FRAME 1100
#define NAME_FRAME "Macron 49.3"

/** GAME SETTING */
#define SIZE_PLAYER 100
#define SIZE_ENEMY 80
#define SIZE_ENEMY_TANK 100
#define SIZE_POWER_UP 50
#define NUMBER_OF_ROCKET 100
#define NUMBER_OF_ENEMY 100
#define ROCKET_SIZE 20
#define ROCKET_ENNEMY_SIZE 10

#define ARRIVAL_RATE (1.0/5) 
#define ENEMIES_TIME 1
#define TIME_EXPLOSION_SPECIAL_ROCKET 50
#define HEALTH_SPECIAL_ENEMY 30
#define HEALTH_ENEMY 10
#define HEALTH_PLAYER 5

#define PADDING_TOP 100
#define NB_POWER_UP 3

#endif